#!/usr/bin/env python3
from pathlib import Path
import argparse

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


def main():
    parser = argparse.ArgumentParser(
        description="Plot token counts per vowel and speaker/audio."
    )

    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="CSV generated by 04_build_vowel_stats.py, containing audio, vowel and n_tokens.",
    )

    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Output image path, for example results/plots/token_counts_by_vowel.png.",
    )

    parser.add_argument(
        "--title",
        type=str,
        default="Token counts by vowel",
        help="Plot title.",
    )

    args = parser.parse_args()

    df = pd.read_csv(args.input)

    required_cols = {"audio", "vowel", "n_tokens"}
    missing = required_cols - set(df.columns)

    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    df = df[["audio", "vowel", "n_tokens"]].copy()
    df["vowel"] = df["vowel"].astype(str)
    df["n_tokens"] = pd.to_numeric(df["n_tokens"], errors="coerce")
    df = df.dropna(subset=["vowel", "n_tokens"])

    # Optional fixed order if these vowels exist.
    preferred_order = ["a", "e", "i", "o", "u"]
    existing_vowels = df["vowel"].unique().tolist()

    vowel_order = [v for v in preferred_order if v in existing_vowels]
    vowel_order += sorted([v for v in existing_vowels if v not in vowel_order])

    # One-dimensional plot:
    # x = number of tokens
    # y = small jitter only to avoid all points being exactly on top of each other
    rng = np.random.default_rng(42)

    plt.figure(figsize=(12, 4))

    for vowel in vowel_order:
        sub = df[df["vowel"] == vowel]

        y = rng.normal(loc=0, scale=0.035, size=len(sub))

        plt.scatter(
            sub["n_tokens"],
            y,
            alpha=0.75,
            s=45,
            label=f"/{vowel}/",
        )

    plt.axhline(0, linewidth=1, alpha=0.4)

    plt.xlabel("Number of tokens")
    plt.yticks([])
    plt.title(args.title)
    plt.legend(title="Vowel")
    plt.grid(axis="x", alpha=0.3)

    args.output.parent.mkdir(parents=True, exist_ok=True)

    plt.tight_layout()
    plt.savefig(args.output, dpi=300)
    plt.close()

    print(f"Saved plot: {args.output}")
    print()
    print("Token count summary by vowel:")
    summary = (
        df.groupby("vowel")["n_tokens"]
        .agg(["count", "mean", "median", "std", "min", "max"])
        .sort_index()
    )
    print(summary)


if __name__ == "__main__":
    main()