from pathlib import Path
from typing import Union

import numpy as np
import pandas as pd


PathLike = Union[str, Path]


def correct_spectrum_csv(
    input_path: PathLike,
    output_path: PathLike
) -> pd.DataFrame:
    """
    Reads either:

    1. A raw spectrum table exported by Praat; or
    2. A standardized spectrum CSV generated by extract_spectrum.

    Keeps only frequency, real and imaginary values, recalculates
    magnitude and phase, and saves a standardized CSV.
    """

    input_path = Path(input_path)
    output_path = Path(output_path)

    if not input_path.exists():
        raise FileNotFoundError(
            f"File not found: {input_path}"
        )

    dataframe = pd.read_csv(input_path)

    raw_praat_columns = [
        "frequency(Hz)",
        "re(Pa/Hz)",
        "im(Pa/Hz)"
    ]

    standardized_columns = [
        "frequency_hz",
        "real",
        "imaginary"
    ]

    has_raw_praat_columns = all(
        column in dataframe.columns
        for column in raw_praat_columns
    )

    has_standardized_columns = all(
        column in dataframe.columns
        for column in standardized_columns
    )

    if has_raw_praat_columns:
        spectrum = dataframe[
            raw_praat_columns
        ].copy()

        spectrum.rename(
            columns={
                "frequency(Hz)": "frequency_hz",
                "re(Pa/Hz)": "real",
                "im(Pa/Hz)": "imaginary"
            },
            inplace=True
        )

    elif has_standardized_columns:
        spectrum = dataframe[
            standardized_columns
        ].copy()

    else:
        raise ValueError(
            "The file does not contain a recognized spectrum format.\n"
            "Expected raw Praat columns: "
            + ", ".join(raw_praat_columns)
            + "\nExpected standardized columns: "
            + ", ".join(standardized_columns)
            + "\nColumns found: "
            + ", ".join(dataframe.columns)
        )

    # Ensure that the required columns are numeric
    for column in standardized_columns:
        spectrum[column] = pd.to_numeric(
            spectrum[column],
            errors="coerce"
        )

    # Remove invalid rows
    spectrum.dropna(
        subset=standardized_columns,
        inplace=True
    )

    # Calculate magnitude
    spectrum["magnitude"] = np.hypot(
        spectrum["real"],
        spectrum["imaginary"]
    )

    # Calculate phase in radians
    spectrum["phase_rad"] = np.arctan2(
        spectrum["imaginary"],
        spectrum["real"]
    )

    # Convert phase to degrees
    spectrum["phase_deg"] = np.degrees(
        spectrum["phase_rad"]
    )

    spectrum.reset_index(
        drop=True,
        inplace=True
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    spectrum.to_csv(
        output_path,
        index=False
    )

    return spectrum